# Generated by Django 2.0.5 on 2018-05-22 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileServer', '0002_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='hashHex',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
